### PR TITLE
fixing json transform

### LINKED ISSUE #4: Check gzip prefix for auto unzipping decision
Every gzip starts with '\x1F' and '\x8B' characters. It would be nice if the lib decides to, in the deserialize operation, to automatic ungzip the information when the buffer starts with these characters, and to not do this otherwise.

This way we could enable and disable compressing in the cache, for example, and the cache reading would working no matter it was compressed or not in the moment of writing

### PR DESCRIPTION
**Pull request by Farenheith**
Closes #4

### CODE REVIEW

File: src/serializer/index.ts [hunk 1]
```diff
@@ -43,19 +43,21 @@ export class Serializer {
 		});
 
 		const stream = await strategy.deserialize(base);
-		const result: Promise<T> = new Promise((resolve) => {
+		base.push(data);
+		base.push(null);
+		return new Promise<T>((resolve) => {
```
Comment (Farenheith) [inline src/serializer/index.ts:48]: I just changed the order because the promise callback is executed after the pushes either way
